use adventure;

drop table if exists `userinfo`;
create table `userinfo` (
`username` varchar(16) not null,
`story_id` tinyint(2) not null default '1',
`current_life` tinyint(3) not null default '100',
`current_gold` tinyint(3) not null default '100',
primary key (`username`)
)ENGINE=MyISAM DEFAULT CHARSET=utf8;








drop table if exists `questions`;
create table `questions` (
`story_id` tinyint(2) not null default '0', 
`story_question_text` text,
`answer_id` tinyint(2) not null default'0', 
`answer_text` text, 
`notes` text,
`goes_to_story_id` tinyint(2) not null default '0',
`health_changes` tinyint(4) not null default '0', 
`gold_changes` tinyint(4) not null default '0',
`image_used` text,
foreign key userinfo(story_id) references userinfo (story_id)
)ENGINE=MyISAM DEFAULT CHARSET=utf8;


insert into `questions` (`story_id`, `story_question_text`, `answer_id`, `answer_text`, `notes`, `goes_to_story_id`, `health_changes`, `gold_changes`, `image_used`)
values ('1', "You're alone in the woods. There's no one around and your phone is dead. Out of the corner of your eye you spot him. Shia LaBeouf. What do you do?", '1', 'Fawn over him! You loved him in Transformers!', 'Not aggressive, but you drop your guard and lose some money.', '2', -20, -30, "shia lacrouch.png"),
('1', "You're alone in the woods. There's no one around and your phone is dead. Out of the corner of your eye you spot him. Shia LaBeouf. What do you do?", '2', 'Get into a powerful stance and shout "JUST DO IT!" ', 'Aggressive. Shia attacks and you suffer a fatal blow. Game over.', '9', -100, -100, "shia lacrouch.png"),
('1', "You're alone in the woods. There's no one around and your phone is dead. Out of the corner of your eye you spot him. Shia LaBeouf. What do you do?", '3', 'You keep walking. Something tells you that something is wrong.', 'Not aggressive, but pushes the story forward safely.', '3', 0, 0, "shia lacrouch.png"),
('1', "You're alone in the woods. There's no one around and your phone is dead. Out of the corner of your eye you spot him. Shia LaBeouf. What do you do?", '4', 'Break into a run. You have seen enough horror movies and late night TV to know that you should not be alone with anyone in the woods.','Aggressive. Leads into chase segment and drops money. Triggers combat', '3', -10, -20, "shia lacrouch.png"),
('2', "You're starstruck feelings blind you to your surroundings. As the two of you get closer, you suddenly find yourself on the ground. You've been suckerpunched by Shia LaBeouf! What's next?!", '1', 'Stand up and hug it out. He seems like a lovable guy, maybe it was a mistake?', 'Aggressive. Shia bites your jugular and you lose consciousness. Game over.', '9', -100, -100,"shia lapunch.jpg"),
('2', "You're starstruck feelings blind you to your surroundings. As the two of you get closer, you suddenly find yourself on the ground. You've been suckerpunched by Shia LaBeouf! What's next?!", '2', "Get up and run! He's out of is mind!", 'Not aggressive, triggers combat.', '3', 0, 0,"shia lapunch.jpg"),
('2', "You're starstruck feelings blind you to your surroundings. As the two of you get closer, you suddenly find yourself on the ground. You've been suckerpunched by Shia LaBeouf! What's next?!", '3', "Return the favor and punch him back! You ain't no sucka!", 'Aggressive. Triggers combat.', '4', -20, +20, "shia lapunch.jpg"),
('2', "You're starstruck feelings blind you to your surroundings. As the two of you get closer, you suddenly find yourself on the ground. You've been suckerpunched by Shia LaBeouf! What's next?!", '4', 'Start insulting him. His modern art is trash and transformers was only good because of Megan Fox.', 'Aggressive. Triggers combat', '4', -40, 0, "shia lapunch.jpg"),
('3', "He's following you about 30 feet back. He gets down on all fours and breaks into a sprint. He's gaining on you. Shia LaBeouf. You're looking for your car, but you're all turned around. He's almost upon you now and you can see there's blood on his face! My god, there's blood everywhere!",'1', "Run for your life! He's crazed and must be escaped at all costs! Is that a knife in his hands? Is this REALLY Hollywood superstar Shia LaBeouf?!", 'Not aggressive. Safely passes story, lose some health out of fear.', '5', -5, 0, "shia lablood.gif"),
('3', "He's following you about 30 feet back. He gets down on all fours and breaks into a sprint. He's gaining on you. Shia LaBeouf. You're looking for your car, but you're all turned around. He's almost upon you now and you can see there's blood on his face! My god, there's blood everywhere!", '2', "Turn back and take him head on. He's just a regular guy with a drinking problem!", 'Aggressive. Triggers combat.', '4', -20, 0, "shia lablood.gif"),
('3', "He's following you about 30 feet back. He gets down on all fours and breaks into a sprint. He's gaining on you. Shia LaBeouf. You're looking for your car, but you're all turned around. He's almost upon you now and you can see there's blood on his face! My god, there's blood everywhere!", '3', "Run! Run far away! You let the adrenaline in your body push you faster and farther than you can imagine!", 'Not aggressive. Lose health out of fear.', '5', -10, 0, "shia lablood.gif"),
('3', "He's following you about 30 feet back. He gets down on all fours and breaks into a sprint. He's gaining on you. Shia LaBeouf. You're looking for your car, but you're all turned around. He's almost upon you now and you can see there's blood on his face! My god, there's blood everywhere!", '4', "You've been waiting your entire life for this moment. The day you can take Shia LaBeouf head on! You want your money back from all the Holes merchandise you bought. You got an old beat up Camaro because of him that didn't even make it to the summer. This is your revenge!", 'Aggressive. Triggers combat.', '4', -10, 20, "shia lablood.gif"),
('4', "The adrenaline flowing through you, you plan take your stand against Shia LaBeouf. He's coming at you, what's your plan?!", '1', "Run up to him and fake him out. Have him collide face first with your fist. Show him who's the boss!", 'Aggressive. Stuns Shia, leads into option to either run or continue fighting.', '6', 0, 20, "shia lastretch.jpg"),
('4', "The adrenaline flowing through you, you plan take your stand against Shia LaBeouf. He's coming at you, what's your plan?!", '2', "You notice the knife in his pocket. You take the first hit just so you can get close enough to steal it. Turn the tables and attack!", 'Aggressive. Continues combat, gain money, lose health.', '7', -20, 20, "shia lastretch.jpg"),
('4', "The adrenaline flowing through you, you plan take your stand against Shia LaBeouf. He's coming at you, what's your plan?!", '3', "Run! Run far away! You let the adrenaline in your body push you faster and farther than you can imagine!", 'Not aggressive. Lose health out of fear.', '5', -10, 20, "shia lastretch.jpg"),
('4', "The adrenaline flowing through you, you plan take your stand against Shia LaBeouf. He's coming at you, what's your plan?!", '4', "Grab him by his rat tail! Not gonna let some weirdo get the best of you!", 'Aggressive. Stuns Shia, leads into option to either run or continue fighting.', '6', -10, 0, "shia lastretch.jpg"),
('5', "Running for your life, from Shia LaBeouf. He's brandishing a knife! Lurking in the shadows, Hollywood superstar Shia LaBeouf. Living in the woods, killing for sport, eating all the bodies... Actual, cannibal Shia LaBeouf! Now it's dark and you seem to have lost him, but you're hopelessly lost yourself. Stranded with a murderer. You creep silently through the underbrush. A-ha! In the distance, a small cottage with a light on. Whatever shall you do?", '1', "Hope! You move stealthily toward it.", 'Moves story along.. BUT YOUR LEG IS CAUGHT IN A BEAR TRAP!!', '8', -30, 0, "shia larun.jpg"),
('5', "Running for your life, from Shia LaBeouf. He's brandishing a knife! Lurking in the shadows, Hollywood superstar Shia LaBeouf. Living in the woods, killing for sport, eating all the bodies... Actual, cannibal Shia LaBeouf! Now it's dark and you seem to have lost him, but you're hopelessly lost yourself. Stranded with a murderer. You creep silently through the underbrush. A-ha! In the distance, a small cottage with a light on. Whatever shall you do?", '2', "Make a break for it! Someone in there might be able to help you!", 'Bear trap', '8', -30, 0, "shia larun.jpg"),
('5', "Running for your life, from Shia LaBeouf. He's brandishing a knife! Lurking in the shadows, Hollywood superstar Shia LaBeouf. Living in the woods, killing for sport, eating all the bodies... Actual, cannibal Shia LaBeouf! Now it's dark and you seem to have lost him, but you're hopelessly lost yourself. Stranded with a murderer. You creep silently through the underbrush. A-ha! In the distance, a small cottage with a light on. Whatever shall you do?", '3', "Try and go around, make sure you aren't being followed before you make another move.", 'Bear trap', '8', -30, 0, "shia larun.jpg"),
('5', "Running for your life, from Shia LaBeouf. He's brandishing a knife! Lurking in the shadows, Hollywood superstar Shia LaBeouf. Living in the woods, killing for sport, eating all the bodies... Actual, cannibal Shia LaBeouf! Now it's dark and you seem to have lost him, but you're hopelessly lost yourself. Stranded with a murderer. You creep silently through the underbrush. A-ha! In the distance, a small cottage with a light on. Whatever shall you do?", '4', "Get far away from the house. Something tells you it isn't where you want to be.", 'Bear trap', '8', -30, 0, "shia larun.jpg"),
('6', "You've got Shia LaBeouf stunned! A feat of strength and skill agains the vicious hunter! He's temporarily incapacitated, what do you take the chance to do?", '1', "You see the knife he has on his person. Take it to make sure you can still keep the upper hand.", 'Acquire weapon', '7', 0, 10, "shia lastun.jpg"),
('6', "You've got Shia LaBeouf stunned! A feat of strength and skill agains the vicious hunter! He's temporarily incapacitated, what do you take the chance to do?", '2', "Run, the moment of sanctuary should be able to give you enough time to escape!", 'Leads back to the cottage.', '5', 0, 10, "shia lastun.jpg"),
('6', "You've got Shia LaBeouf stunned! A feat of strength and skill agains the vicious hunter! He's temporarily incapacitated, what do you take the chance to do?", '3', "Look for a nearby rock. End the madness now!", 'Curb stomp dat foo', '7', 0, 10, "shia lastun.jpg"),
('6', "You've got Shia LaBeouf stunned! A feat of strength and skill agains the vicious hunter! He's temporarily incapacitated, what do you take the chance to do?", '4', "Attack him! If and when get wakes back up, make sure he's slowed down heavily! Make a run for it into the forest after that!", 'Cripple shot and run!', '5', 0, 0, "shia lastun.jpg"),
('7', "You've take then knife from Shia LaBeouf. You've got the upper hand and can either end it now or make a break for it!", '1', "Throw the knife far away in the opposite direction. Use this as an opportunity to level the playing field as you escape deeper into the forest!", 'Distract, run', '5', 0, -10, "shia lanude.jpg"), 
('7', "You've take then knife from Shia LaBeouf. You've got the upper hand and can either end it now or make a break for it!", '2', "Cut off his rat tail, throw it down by him in a display of dominance leave.", 'Still run', '5', 0, 5, "shia lanude.jpg"), 
('7', "You've take then knife from Shia LaBeouf. You've got the upper hand and can either end it now or make a break for it!", '3', "Keep the knife, but flee the scene. It's dangerous to be here.", 'run', '5', 0, 0, "shia lanude.jpg"), 
('7', "You've take then knife from Shia LaBeouf. You've got the upper hand and can either end it now or make a break for it!", '4', "You can't muster the nerve to end the madness, so you make sure to cover your tracks well. Create a fake path leading to no where as you escape", 'run', '5', 0, 0, "shia lanude.jpg"), 
('8', "You move stealthily toward it, But your leg! Ah! It's caught in a bear trap!", '1', "Woozy, you fall over and lose consciousnes. You can't handle the sight of blood.", 'Game Over', '9', -100, 0, "shia lanude.jpg"), 
('8', "You move stealthily toward it, But your leg! Ah! It's caught in a bear trap!", '2', "You know you need to move forward at any cost. So you start gnawing off your leg quietly and limp towards the cottage.", 'Move Story', '10', -20, 0, "shia lanude.jpg"), 
('8', "You move stealthily toward it, But your leg! Ah! It's caught in a bear trap!", '3', "Getting a second rush of adrenaline, you try to pry open the bear trap.", 'Move Story', '10', -60, 0, "shia lanude.jpg"), 
('8', "You move stealthily toward it, But your leg! Ah! It's caught in a bear trap!", '4', "Joke's on the hunter, you've got a prosthetic leg! Well, you did in a dream anyway...", 'Move Story', '9', -100, 0, "shia lanude.jpg"), 
('9', "Game over. You've been defeated by Shia LaBeouf.", '1', "Try again.", 'Move Story', '1', 100, 100, "shia lawoods.png"), 
('9', "Game over. You've been defeated by Shia LaBeouf.", '1', "You really have to.", 'Move Story', '1', 100, 100, "shia lawoods.png"), 
('9', "Game over. You've been defeated by Shia LaBeouf.", '1', "You don't have any choice.", 'Move Story', '1', 100, 100, "shia lawoods.png"), 
('9', "Game over. You've been defeated by Shia LaBeouf.", '1', "Yes. Again.", 'Move Story', '1', 100, 100, "shia lawoods.png"), 
('10', "Gnawing off your leg quietly, limping toward the cottage quietly. Now you're on the doorstep sitting inside, Shia LaBeouf. Sharpening an ax, but he doesn't hear you enter. You're sneaking up behind him. Strangling superstar Shia LaBeouf. Fighting for your life with Shia LaBeouf! Wrestling a knife from Shia LaBeouf! Stab it in his kidney! Safe at last from Shia LaBeouf.", '1', "Congrats! You're finally safe... From Shia LaBeouf... Press to play again!", 'Move Story', '1', 100, 100, "shia lasafe.png"),
('10', "Gnawing off your leg quietly, limping toward the cottage quietly. Now you're on the doorstep sitting inside, Shia LaBeouf. Sharpening an ax, but he doesn't hear you enter. You're sneaking up behind him. Strangling superstar Shia LaBeouf. Fighting for your life with Shia LaBeouf! Wrestling a knife from Shia LaBeouf! Stab it in his kidney! Safe at last from Shia LaBeouf.", '1', "You really are, don't worry. Let's play again.", 'Move Story', '1', 100, 100, "shia lasafe.png"),
('10', "Gnawing off your leg quietly, limping toward the cottage quietly. Now you're on the doorstep sitting inside, Shia LaBeouf. Sharpening an ax, but he doesn't hear you enter. You're sneaking up behind him. Strangling superstar Shia LaBeouf. Fighting for your life with Shia LaBeouf! Wrestling a knife from Shia LaBeouf! Stab it in his kidney! Safe at last from Shia LaBeouf.", '1', "Boo! He's behind! Nah, just kidding. You are the winner!", 'Move Story', '1', 100, 100, "shia lasafe.png"),
('10', "Gnawing off your leg quietly, limping toward the cottage quietly. Now you're on the doorstep sitting inside, Shia LaBeouf. Sharpening an ax, but he doesn't hear you enter. You're sneaking up behind him. Strangling superstar Shia LaBeouf. Fighting for your life with Shia LaBeouf! Wrestling a knife from Shia LaBeouf! Stab it in his kidney! Safe at last from Shia LaBeouf.", '1', "Ta dah! You are the best!", 'Move Story', '1', 100, 100, "shia lasafe.png");
